openapi: '3.0.2'
info:
  title: SpeedPanel Core API
  version: '0.1'
servers:
  - url: https://{host}:{port}/api/v1
    variables:
      "host": 
        default: localhost
      "port":
        default: "80"
security:
  - jwtUserToken: []
  - apiKeyPrivate: []
paths:
  /network:
    post:
      parameters:
        - in: "cookie"
          name: "name"
          required: true
          schema:
            type: string
      security:
        - jwtUserToken: []
        - apiKeyPrivate: []
      responses:
        '201':
          description: Success
          content:
            "application/json":
              schema:
                "$ref": '#/components/schemas/NetworkCreateSuccess'
  /{networkID}/container:
    post:
      parameters:
        - in: path
          name: networkID
          required: true
          schema:
            type: string
        - in: header
          name: X-Docker-Image
          required: true
          schema:
            type: string
      security:
        - jwtUserToken: []
        - apiKeyPrivate: []
      requestBody:
        description: Must be JSON only
        content:
          "application/json":
            schema:
              "$ref": "#/components/schemas/ContainerCreateRequestBody"
      responses:
        '201':
          description: Success
          content:
            "application/json":
              schema:
                "$ref": "#/components/schemas/ServerCreateSuccess"
  /{service}:
    patch:
      parameters:
        - in: path
          name: service
          required: true
          schema:
            type: string
        - in: header
          name: Network-ID
          required: false
          schema:
            type: string
        - in: header
          name: Version
          required: false
          schema:
            type: string
            pattern: ^([0-9]+\.[0-9]+(\.[0-9]+)?)$
        - in: header
          name: Port
          required: false
          schema:
            type: integer
      security:
        - jwtUserToken: []
        - apiKeyPrivate: []
      responses:
        '200':
          "$ref": "#/components/responses/UpdateResponse"
        '500':
          description: Internal Server Error
  /{service}/console:
    post:
      parameters:
        - in: path
          name: service
          required: true
          schema:
            type: string
        - in: header
          name: X-RCON-Pass
          required: true
          schema:
            type: string
      security:
        - jwtUserToken: []
        - apiKeyPrivate: []
      responses:
        '200':
          description: Success
        '401':
          description: RCON unauthorised
        '500':
          description: Internal RCON Error
    delete:
      parameters:
        - in: path
          name: service
          required: true
          schema:
            type: string
      security:
        - jwtUserToken: []
        - apiKeyPrivate: []
      responses:
        '200':
          description: Successful rcon client shutdown
        '500':
          description: An error occured while closing connection to remote console
    get:
      parameters:
        - in: path
          name: service
          required: true
          schema:
            type: string
      security:
        - jwtUserToken: []
        - apiKeyPrivate: []
      responses:
        default:
          description: Stream from docker Service logs.
          content:
            "text/event-stream":
              schema:
                type: object
                x-events:
                  added:
                    type: object
                    properties:
                      message:
                        type: string
                      createdAt:
                        type: string
                        format: date-time
                      updated:
                        type: object
                        properties:
                          previous:
                            type: string
                          newValue:
                            type: string
                          updatedAt:
                            type: string
                            format: date-time
          headers:
            "Connection":
              schema:
                type: string
                enum: ["Keep-Alive"]
  /{service}/plugins:
    patch:
      parameters:
        - in: path
          name: service
          required: true
          schema:
            type: string
        - in: header
          name: X-Plugin-ID
          required: true
          schema:
            type: string
      responses:
        '200':
          "$ref": "#/components/responses/UpdateResponse"
        '208':
          description: "plugin already present"
        '401':
          description: "attempted unauthorised update of container"
        '500':
          description: "Internal Server Error"
    delete:
      parameters:
        - in: path
          name: service
          required: true
          schema:
            type: string
        - in: header
          name: X-Plugin-ID
          required: true
          schema:
            type: string
      responses:
        '200':
          "$ref": "#/components/responses/UpdateResponse"
        '208':
          description: "plugin already present"
        '401':
          description: "attempted unauthorised update of container"
        '500':
          description: "Internal Server Error"
components:
  responses:
    UpdateResponse:
      description: Success
      content:
        "application/json":
          schema:
            type: object
            properties:
              Warnings:
                type: array
                items:
                  type: string
  schemas:
    NetworkCreateSuccess:
      type: object
      properties:
        network_response:
          "$ref": "#/components/schemas/NetworkCreateResponseDocker"
        database_response:
          nullable: false
          type: object
          properties:
            network_id:
              type: string
            owner_id:
              type: string
            team:
              type: boolean
    NetworkCreateResponseDocker:
      type: object
      properties:
        Id:
          type: string
          nullable: false
        Warning:
          type: string
          nullable: true
    ContainerCreateRequestBody:
      type: object
      properties:
        name:
          type: string
          nullable: false
        hostname: 
          type: string
          nullable: false
          pattern: ^(?=.{1,255}$)[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?(?:\.[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?)*\.?$
        version:
          type: string
          nullable: false
        type:
          type: string
          nullable: false
        premium:
          type: boolean
          nullable: false
        modpack:
          type: string
          nullable: true
    ServiceCreateResponse:
      type: object
      properties:
        ID:
          type: string
          nullable: false
        Warnings:
          type: array
          nullable: true
          items:
            type: string
    MongoInsertResult:
      type: object
      properties:
        InsertedID:
          type: string
    MongoUpdateResult:
      type: object
      properties:
        MatchedCount:
          type: integer
        ModifiedCount:
          type: integer
        UpsertedCount:
          type: integer
        UpsertedID:
          type: string
    ServerCreateSuccess:
      type: object
      properties:
        server_create:
          "$ref": "#/components/schemas/ServiceCreateResponse"
        server_insert_result:
          "$ref": "#/components/schemas/MongoInsertResult"
        network_update_result:
          "$ref": "#/components/schemas/MongoUpdateResult"
        
  securitySchemes:
    jwtUserToken:
      type: http
      description: "A JWT token containing the data of the user."
      scheme: "bearer"
      bearerFormat: "Json Object containing the user's id, the username, the Team's Id if the user is in one or -1 if he isn't and the name of the subscription plan as defined in the config.toml file."
    apiKeyPrivate:
      type: apiKey
      in: header
      name: X-API-Key
      description: Server side API-Keys defined in the config.toml file. Used by the frontend to make requests to the core.
